version: '3.7'
services:

  prometheus:
    image: prom/prometheus:latest
    networks:
      - skynet
    volumes:
      - /mnt/hidrive/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/hidrive/metrics:/prometheus
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.qaybe.de`)"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls.certresolver=sec"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  grafana:
    image: grafana/grafana
    networks:
      - skynet
    depends_on:
      - prometheus
      - pushgateway
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.qaybe.de`)"
        - "traefik.http.routers.grafana.tls.certresolver=sec"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/hidrive/grafana:/var/lib/grafana
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.qaybe.de"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      #- "GF_SMTP_ENABLED=true"
      #- "GF_SMTP_HOST=smtp.1blu.de"
      #- "GF_SMTP_USER=r284141_0-common"
      #- "GF_SMTP_PASSWORD="
      
networks:
    skynet:
        external: true
volumes:
  grafana:
  prometheus:
